/**
 * Shared column names and dashboard constants.
 */
CheckBack.Dashboard.Constants = {
  GYR_COL: '(G/Y/R)',
  LEGACY_GYR_COL: ' (G/Y/R)',
  /** Merged license column (provisioned/entitled pairs). Legacy split cols still supported in parsers. */
  LICENSE_COL: 'Provisioned/Entitled Lic Calling',
  LEGACY_ENTITLED_COL: 'Entitled Lic Calling',
  LEGACY_PROVISIONED_COL: 'Providioned Lic Calling',
  WEBEX_ORG_ADMIN_PREFIX: 'https://admin.webex.com/help-desk/org/',
  CCRC_SUB_DETAIL_PREFIX: 'https://ccrc.cisco.com/subscriptions/detail/',
  DEFAULT_LINK_ORDER: ['S&C', 'Success Portal'],
  ADDON_ROWS: [
    'PSTN Cisco Calling Plans',
    'Customer Assist',
    'Attendant Console',
    'AI Receptionist',
    'AI Premium',
  ],
  PORTFOLIO_COLUMN_PREFER: [
    'Opportunity Name',
    '(G/Y/R)',
    'Customer org id',
    'TCV $',
    'AAR $',
    'Platforms',
    'Partner',
    'SL2',
    'Sub #',
    'Provisioned/Entitled Lic Calling',
    'Active Lic Calling',
  ],
  /** Canonical export order from samples/check_back_template_v1.xlsx */
  TEMPLATE_COLUMN_ORDER: [
    'Opportunity Name',
    'Opportunity (linked)',
    'SL2',
    'TCV $',
    'Closed on (MM/YY)',
    'Competitor',
    'Migrating from',
    'Migrating to',
    'Partner',
    'CSM Engagement Model (linked)',
    'CSM name',
    'Sub #',
    'Sub Term',
    'Sub start date (MM/DD/YYYY)',
    'Add-ons included or not',
    'Calling Setup Assist included (Y/N)',
    'Provisioned/Entitled Lic Calling',
    'Active Lic Calling',
    'Customer org id',
    'Notes from Calling Analytics',
    'Notes from provisioned features',
    'CCEP trial (Y/N)',
    '(G/Y/R)',
    'TAC/BEMS',
    'AAR $',
    'Collab AE/SE',
    'Service lines',
    'Sub term (months)',
    'Subscription dates',
    'Platforms',
    'Trend active users 90d',
    'Trend call volume 90d',
    'Lic Professional (used/entitled)',
    'Lic Standard (used/entitled)',
    'Lic Workspace (used/entitled)',
    'Active % of provisioned',
    'External calls',
    'Meetings usage',
    'Messaging usage',
    'Auto Attendant count',
    'Hunt Groups count',
    'Call Queues count',
    'Connected-UC (Y/N)',
    'Virtual Lines count',
    'Data gathered by',
    'Data gathered date',
    'Salesforce URL',
  ],
  BIA_CANONICAL_COLS: new Set([
    'Opportunity Name',
    'Customer org id',
    '(G/Y/R)',
    'TCV $',
    'AAR $',
    'Sub #',
    'Subscription dates',
    'Sub term (months)',
    'Platforms',
    'Partner',
    'SL2',
    'Collab AE/SE',
    'CSM Engagement Model (linked)',
    'Provisioned/Entitled Lic Calling',
    'Active Lic Calling',
    'Lic Professional (used/entitled)',
    'Lic Standard (used/entitled)',
    'Lic Workspace (used/entitled)',
    'Meetings usage',
    'Messaging usage',
    'External calls',
    'Auto Attendant count',
    'Hunt Groups count',
    'Call Queues count',
    'Connected-UC (Y/N)',
    'Virtual Lines count',
    'Active % of provisioned',
    'Data gathered by',
    'Data gathered date',
    'Notes from Calling Analytics',
    'Calls busiest hour',
    'Trend active users 90d',
    'Trend call volume 90d',
  ]),
  WORKBOOK_SUPPLEMENT_COLS: [
    'Opportunity (linked)',
    'Salesforce URL',
    'Closed on (MM/YY)',
    'Competitor',
    'Migrating from',
    'Migrating to',
    'Success Portal',
    'CSM name',
    'Sub Term',
    'Sub start date (MM/DD/YYYY)',
    'Add-ons included or not',
    'Calling Setup Assist included (Y/N)',
    'CCEP trial (Y/N)',
    'Notes from provisioned features',
    'Trial',
    'Final Determination',
    'Recommended Actions',
    'TAC/BEMS',
    'Control Hub Helpdesk',
  ],
};
